### ISSUE TITLE
codepath to cleanly exit the game

### ISSUE THREAD

**Issue by timoschwarzer** [sparkle-preference/OriWotwRandomizerClient#140]
currently exiting hangs, and @MunWolf's keybinding that closes via ahk sometimes leaves dangling file handles on the dlls

**Comment by MunWolf** [comment]
Maybe look into just calling exit(0) at some point and see if it cleanly exits.
WotW doesn't cleanly exit for me even in the vanilla game.

**Comment by MunWolf** [comment]
https://github.com/sparkle-preference/OriWotwRandomizerClient/commit/ced59455515d408fa6463fec389fa3e358731154
This is as clean as we can get it, game still crashes at least on my dev setup because of access violations in GameOverlayRenderer64.dll but I see no evidence of that being our fault, so closing this.
