### ISSUE TITLE
Adding a hint to Twillen's shop

### ISSUE THREAD

**Issue by toadettexmushina** [sparkle-preference/OriWotwRandomizerClient#99]
Have another skill hint in Twillen's shop, in addition to the ones from Opher and Lupo. This would allow for more skills having hints, or just more possible distributions. 

Current Setup:
Opher hint: Bash / Glide / Bow / Clean Water
Lupo hint: Burrow / Water Dash / Grenade / Flap

Potential Setups (adding Flash back in, for the sake of moki players):

Opher: Bash / Bow / Burrow
Lupo: Clean Water / Grenade / Flap
Twillen: Water Dash / Glide / Flash

Opher: Bash / Grenade / Flap
Lupo: Clean Water / Water Dash / Burrow
Twillen: Bow / Flash / Glide

Other possibillities:
Adding skills, such as:
Dash - go fast mode
Launch - yeah, this would be totally broken
Hammer/Spike - break ALL the floors
Grapple - This comes into play surprisingly often
Sentry - for those sweet sweet sjumps
Blaze - memes
Regenerate - heelz plz
Shuriken - what are walls anyway?
Double Jump - I'm just listing everything at this point

**Comment by SiriusAshling** [comment]
An alternate hints header exists since a while, feel free to try it [](https://discord.com/channels/488789611062231055/711341625208471562/809463738247413840)
It uses the following distribution:
Opher: Water / Glide / Flap ("Get into the locked lategame areas")
Lupo: Burrow / Grenade / Waterdash / Flap ("Abilities from the lategame areas")
Twillen: Bash / Bow ("Common strict abilitylocks")
Which aims to follow memorable patterns as well as group abilities by how early you may need them to have better control over proper pricing.

Using the header system you can customize the hints to any of your suggestions as well if you want to try them, if you request simple headers like that in the dev discord me or cosmic will probably write it up.
